### ISSUE TITLE
Update all private information

### ISSUE THREAD

**Issue by le4ker** [vkampouris/pokemownbeta#2]
All the private information that was exposed in the [cofnig](https://github.com/vkampouris/pokemownbeta/blob/master/config/config.ini) need to be deleted from the repo and update their values on [heroku config](https://dashboard.heroku.com/apps/pokemownbeta/settings).

**Comment by vkampouris** [comment]
Wtf ahahhahahahahahah

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
